server:
  port: 8081


app:
  name: ecommerce_api
  version: 1.0.0
  openapi:
    dev-url: samlogy.com

  springdoc:
    api-docs:
      path: /samlogy-api-docs
    packages-to-scan: com.samlogy.spring.swagger.controller
    swagger-ui:
      filter: true
      operationsSorter: method
      path: /samlogy-documentation
      tagsSorter: alpha
      tryItOutEnabled: true

spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop #validate create-drop
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/my-realm

  flyway:
    baselineOnMigrate:  true
    enabled: true
    locations: classpath:db.migration
    baseline-on-migrate: true

  profiles:
    active: int

javamelody:
  enabled: true
  excluded-datasources: secretSource,topSecretSource
  spring-monitoring-enabled: true
  init-parameters:
    log: false

logging:
  level:
    org:
      springframework:
        security: TRACE