pipeline {
    agent any
    environment {
        DOCKER_REGISTRY = 'your_docker_registry'
        DOCKER_CREDENTIALS_ID = 'your_docker_credentials_id'
        IMAGE_NAME = 'spring_api'
        IMAGE_TAG = '1.0'
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/Samlogy/java-spring-project.git', branch: 'deploy'
            }
        }
        stage('Build') {
            steps {
                sh './mvnw clean install -DskipTests'
            }
        }
        stage('Test') {
            steps {
                sh './mvnw test'
            }
        }
        stage('Build Docker Image') {
             steps {
                script {
                    def app = docker.build("${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}")
//                     sh 'docker build -t sammmmmm/spring-api:1.0 .'
                }
             }
        }
        stage('Push Docker Image') {
            script {
                docker.withRegistry('', DOCKER_CREDENTIALS_ID) {
                    app.push("${IMAGE_TAG}")
                }
            }
        }
    }

    post {
        success {
            echo 'Build and Deploy succeeded!'
        }
        failure {
            echo 'Build or Deploy failed!'
        }
    }
}